import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { fetchPictures } from "../utils/fetchPictures";
import { fetchPriceCards } from "../utils/fetchPriceCards";

interface Props {
  pictures: Picture[];
  priceCards: PriceCard[];
}

export default function Home({ pictures, priceCards }: Props) {
  console.log(pictures);
  console.log(priceCards);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">Simple text</div>
    </div>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pictures = await fetchPictures();
  const priceCards = await fetchPriceCards();

  return {
    props: {
      pictures,
      priceCards,
    },
  };
};
